// Seed data for initial database population
// Products mirror eshop.js, blog posts mirror blog.html, media from /img/gallery/

var SEED_PRODUCTS = [
    { id: 1, name: 'Hondata K-Pro4', name_en: 'Hondata K-Pro4', category: 'ecu', price: 22542, desc: 'Kompletní řídicí jednotka pro Honda K-series motory. Plný přístup k mapám.', desc_en: 'Complete ECU for Honda K-series engines. Full map access and datalogging.', badge: 'bestseller', stock: 5, img: '/img/products/kpro.png', desc_long: 'Hondata K-Pro4 je nejpokročilejší standalone ECU pro Honda K-series motory.', desc_long_en: 'Hondata K-Pro4 is the most advanced standalone ECU for Honda K-series engines.', specs: [['Typ', 'Standalone ECU'], ['Kompatibilita', 'Honda K20A, K20Z, K24A']], specs_en: [['Type', 'Standalone ECU'], ['Compatibility', 'Honda K20A, K20Z, K24A']] },
    { id: 2, name: 'Hondata S300 V3', name_en: 'Hondata S300 V3', category: 'ecu', price: 18990, desc: 'Plug-in ECU pro OBD1 Honda. Datalogging, launch control, boost control.', desc_en: 'Plug-in ECU for OBD1 Honda. Datalogging, launch control, boost control.', badge: '', stock: 3, img: '/img/products/ecu-obd1.png', desc_long: 'Hondata S300 V3 je plug-in ECU deska pro originální OBD1 řídící jednotku Honda.', desc_long_en: 'Hondata S300 V3 is a plug-in ECU board for the original Honda OBD1 ECU.', specs: [['Typ', 'Plug-in ECU deska'], ['Kompatibilita', 'OBD1 Honda (P28, P72, P30)']], specs_en: [['Type', 'Plug-in ECU board'], ['Compatibility', 'OBD1 Honda (P28, P72, P30)']] },
    { id: 3, name: 'Hondata FlashPro', name_en: 'Hondata FlashPro', category: 'ecu', price: 15750, desc: 'Flash tuning pro Honda Civic Si, Accord, CR-Z. OBD2 diagnostika.', desc_en: 'Flash tuning for Honda Civic Si, Accord, CR-Z. OBD2 diagnostics.', badge: 'new', stock: 8, img: '/img/products/kryt-ecu.png', desc_long: 'Hondata FlashPro je flash tuning zařízení pro moderní Honda vozy s OBD2.', desc_long_en: 'Hondata FlashPro is a flash tuning device for modern Honda vehicles with OBD2.', specs: [['Typ', 'Flash tuner (OBD2)'], ['Kompatibilita', 'Civic Si, Accord, CR-Z']], specs_en: [['Type', 'Flash tuner (OBD2)'], ['Compatibility', 'Civic Si, Accord, CR-Z']] },
    { id: 4, name: 'Kabeláž pro K-swap', name_en: 'K-swap wiring harness', category: 'ecu', price: 8490, desc: 'Kompletní kabeláž pro swap K-series motoru do starších Honda Civic.', desc_en: 'Complete wiring harness for K-series engine swap into older Honda Civic.', badge: '', stock: 4, img: '/img/products/civky-uchyt.png', desc_long: 'Kompletní kabelový svazek pro swap K-series motoru (K20, K24).', desc_long_en: 'Complete wiring harness for K-series engine swap (K20, K24).', specs: [['Použití', 'K-swap do EG/EK/CRX'], ['ECU', 'Hondata K-Pro kompatibilní']], specs_en: [['Usage', 'K-swap into EG/EK/CRX'], ['ECU', 'Hondata K-Pro compatible']] },
    { id: 5, name: 'Set silentbloků Civic EG', name_en: 'Bushing set Civic EG', category: 'silentbloky', price: 3890, desc: 'Kompletní sada PU silentbloků pro Honda Civic EG (92–95). Shore 80A.', desc_en: 'Complete PU bushing set for Honda Civic EG (92–95). Shore 80A.', badge: 'bestseller', stock: 15, img: '/img/products/silentblok-14h.png', desc_long: 'Kompletní sada polyuretanových silentbloků Silponix pro Honda Civic 5. generace.', desc_long_en: 'Complete Silponix polyurethane bushing set for Honda Civic 5th gen.', specs: [['Materiál', 'Polyuretan (PU)'], ['Tvrdost', 'Shore 80A'], ['Kompatibilita', 'Honda Civic EG (1992–1995)']], specs_en: [['Material', 'Polyurethane (PU)'], ['Hardness', 'Shore 80A'], ['Compatibility', 'Honda Civic EG (1992–1995)']] },
    { id: 6, name: 'Set silentbloků Civic EK', name_en: 'Bushing set Civic EK', category: 'silentbloky', price: 3890, desc: 'Kompletní sada PU silentbloků pro Honda Civic EK (96–00). Shore 80A.', desc_en: 'Complete PU bushing set for Honda Civic EK (96–00). Shore 80A.', badge: '', stock: 12, img: '/img/products/silentblok-106h.png', desc_long: 'Kompletní sada polyuretanových silentbloků Silponix pro Honda Civic 6. generace.', desc_long_en: 'Complete Silponix polyurethane bushing set for Honda Civic 6th gen.', specs: [['Materiál', 'Polyuretan (PU)'], ['Tvrdost', 'Shore 80A']], specs_en: [['Material', 'Polyurethane (PU)'], ['Hardness', 'Shore 80A']] },
    { id: 7, name: 'Silentblok zadní nápravy ITR', name_en: 'Rear axle bushing ITR', category: 'silentbloky', price: 1290, desc: 'Polyuretanový silentblok zadní nápravy pro Integra Type R DC2.', desc_en: 'Polyurethane rear axle bushing for Integra Type R DC2.', badge: '', stock: 20, img: '/img/products/silentblok-212h.png', desc_long: 'Vysoce odolný polyuretanový silentblok zadní nápravy pro Honda Integra Type R (DC2).', desc_long_en: 'Highly durable polyurethane rear axle bushing for Honda Integra Type R (DC2).', specs: [['Materiál', 'Polyuretan (PU)'], ['Kompatibilita', 'Honda Integra Type R DC2']], specs_en: [['Material', 'Polyurethane (PU)'], ['Compatibility', 'Honda Integra Type R DC2']] },
    { id: 8, name: 'Silentblok předního ramene', name_en: 'Front arm bushing', category: 'silentbloky', price: 890, desc: 'PU silentblok předního spodního ramene. Civic EG/EK, Integra DC2.', desc_en: 'PU front lower arm bushing. Civic EG/EK, Integra DC2.', badge: '', stock: 25, img: '/img/products/vazelina.jpg', desc_long: 'Polyuretanový silentblok předního spodního ramene vlastní výroby Silponix.', desc_long_en: 'Polyurethane front lower arm bushing manufactured by Silponix.', specs: [['Materiál', 'Polyuretan (PU)'], ['Kompatibilita', 'Civic EG/EK, Integra DC2, CR-V RD1']], specs_en: [['Material', 'Polyurethane (PU)'], ['Compatibility', 'Civic EG/EK, Integra DC2, CR-V RD1']] },
    { id: 9, name: 'Dvouřadá řemenice B-series RED', name_en: 'Dual pulley B-series RED', category: 'motor', price: 5324, desc: 'SET červená dvouřadá řemenice pro Honda B-series. Eloxovaný hliník.', desc_en: 'SET red dual pulley for Honda B-series. Anodised aluminium.', badge: 'bestseller', stock: 6, img: '/img/products/remenice-red.png', desc_long: 'SET dvouřadých řemenic v červeném eloxovaném provedení pro Honda B-series motory.', desc_long_en: 'SET of dual pulleys in red anodised finish for Honda B-series engines.', specs: [['Materiál', 'Hliník 6061-T6'], ['Kompatibilita', 'Honda B16A, B16B, B18C']], specs_en: [['Material', 'Aluminium 6061-T6'], ['Compatibility', 'Honda B16A, B16B, B18C']] },
    { id: 10, name: 'Jednořadá řemenice B-series', name_en: 'Single pulley B-series', category: 'motor', price: 2904, desc: 'Odlehčená jednořadá řemenice pro B16/B18. CNC obráběný hliník.', desc_en: 'Lightweight single pulley for B16/B18. CNC machined aluminium.', badge: '', stock: 8, img: '/img/products/remenice-red.png', desc_long: 'Odlehčená jednořadá kliková řemenice pro závodní aplikace.', desc_long_en: 'Lightweight single groove crank pulley for race applications.', specs: [['Materiál', 'Hliník 6061-T6'], ['Typ', 'Jednořadá']], specs_en: [['Material', 'Aluminium 6061-T6'], ['Type', 'Single groove']] },
    { id: 11, name: 'Dvouřadá řemenice B-series GOLD', name_en: 'Dual pulley B-series GOLD', category: 'motor', price: 3630, desc: 'SET zlatá dvouřadá řemenice pro Honda B-series. Eloxovaný hliník.', desc_en: 'SET gold dual pulley for Honda B-series. Anodised aluminium.', badge: 'new', stock: 4, img: '/img/products/remenice-red.png', desc_long: 'SET dvouřadých řemenic ve zlatém eloxovaném provedení pro Honda B-series.', desc_long_en: 'SET of dual pulleys in gold anodised finish for Honda B-series engines.', specs: [['Materiál', 'Hliník 6061-T6'], ['Povrch', 'Zlatý tvrdý elox']], specs_en: [['Material', 'Aluminium 6061-T6'], ['Finish', 'Gold hard anodised']] },
    { id: 12, name: 'Nerezový úchyt cívek CPR', name_en: 'Stainless coil bracket CPR', category: 'motor', price: 1029, desc: 'Nerezový úchyt zapalovacích cívek CPR Modul pro K-series motory.', desc_en: 'Stainless steel CPR ignition coil bracket for K-series engines.', badge: '', stock: 10, img: '/img/products/civky-uchyt.png', desc_long: 'Nerezový úchyt zapalovacích cívek CPR Modul z leštěné nerezové oceli.', desc_long_en: 'Stainless steel CPR Module ignition coil bracket from polished stainless steel.', specs: [['Materiál', 'Nerezová ocel AISI 304'], ['Kompatibilita', 'Honda K20, K24']], specs_en: [['Material', 'Stainless steel AISI 304'], ['Compatibility', 'Honda K20, K24']] },
    { id: 13, name: 'Vzpěra předního stabilizátoru', name_en: 'Front anti-roll bar link', category: 'podvozek', price: 460, desc: 'Vzpěra předního stabilizátoru 14-H. Zesílená verze pro motorsport.', desc_en: 'Front anti-roll bar link 14-H. Reinforced motorsport version.', badge: '', stock: 30, img: '/img/products/silentblok-14h.png', desc_long: 'Zesílená vzpěra předního stabilizátoru Silponix 14-H pro motorsport.', desc_long_en: 'Reinforced Silponix 14-H front anti-roll bar link for motorsport.', specs: [['Materiál', 'Ocel, zesílená'], ['Kompatibilita', 'Civic EG/EK, Integra DC2, CRX']], specs_en: [['Material', 'Steel, reinforced'], ['Compatibility', 'Civic EG/EK, Integra DC2, CRX']] },
    { id: 14, name: 'Čep spodní 555 Japan', name_en: 'Lower ball joint 555 Japan', category: 'podvozek', price: 760, desc: 'Kulový čep spodního ramene 555 Japan. Civic, CRX, Integra, CR-V.', desc_en: 'Lower arm ball joint 555 Japan. Civic, CRX, Integra, CR-V.', badge: '', stock: 20, img: '/img/products/cep-spodni.jpg', desc_long: 'Prémiový kulový čep spodního ramene od japonského výrobce 555 (Sankei).', desc_long_en: 'Premium lower arm ball joint from Japanese manufacturer 555 (Sankei).', specs: [['Výrobce', '555 (Sankei), Japonsko'], ['Kvalita', 'OEM ekvivalent']], specs_en: [['Manufacturer', '555 (Sankei), Japan'], ['Quality', 'OEM equivalent']] },
    { id: 15, name: 'Rohová výztuha nosníků', name_en: 'Corner brace reinforcement', category: 'podvozek', price: 726, desc: 'Rohová výztuha předních nosníků C5G, C6G, CRX. Pár (levá + pravá).', desc_en: 'Front rail corner brace C5G, C6G, CRX. Pair (left + right).', badge: 'new', stock: 8, img: '/img/products/rohova-vyztuha.jpg', desc_long: 'Rohová výztuha předních nosníků vlastní výroby Silponix.', desc_long_en: 'Front rail corner brace manufactured by Silponix.', specs: [['Materiál', 'Ocelový plech 2 mm'], ['Kompatibilita', 'Civic EG, EK, CRX']], specs_en: [['Material', 'Steel sheet 2 mm'], ['Compatibility', 'Civic EG, EK, CRX']] },
    { id: 16, name: 'Silentblok stabilizátoru', name_en: 'Anti-roll bar bushing', category: 'podvozek', price: 350, desc: 'PU silentblok předního stabilizátoru. Průměr 22/24/26 mm.', desc_en: 'PU front anti-roll bar bushing. Diameter 22/24/26 mm.', badge: '', stock: 40, img: '/img/products/silentblok-106h.png', desc_long: 'Polyuretanový silentblok předního stabilizátoru vlastní výroby Silponix.', desc_long_en: 'Polyurethane front anti-roll bar bushing manufactured by Silponix.', specs: [['Materiál', 'Polyuretan (PU)'], ['Průměry', '22 / 24 / 26 mm']], specs_en: [['Material', 'Polyurethane (PU)'], ['Diameters', '22 / 24 / 26 mm']] },
    { id: 17, name: 'Zámek kapoty NEREZ', name_en: 'Bonnet lock STAINLESS', category: 'karoserie', price: 593, desc: 'Nerezový závodní zámek kapoty. Set obsahuje 2 kusy + příslušenství.', desc_en: 'Stainless steel racing bonnet lock. Set includes 2 pcs + hardware.', badge: '', stock: 15, img: '/img/products/zamek-kapoty.png', desc_long: 'Závodní zámek kapoty z nerezové oceli.', desc_long_en: 'Racing bonnet lock made from stainless steel.', specs: [['Materiál', 'Nerezová ocel'], ['Balení', '2 ks + kontra-díly']], specs_en: [['Material', 'Stainless steel'], ['Package', '2 pcs + counter-parts']] },
    { id: 18, name: 'Čep kapoty NEREZ set', name_en: 'Bonnet pin set STAINLESS', category: 'karoserie', price: 890, desc: 'Nerezové čepy kapoty se závlačkami. Závodní provedení, set 2 ks.', desc_en: 'Stainless steel bonnet pins with clips. Race-spec, set of 2.', badge: '', stock: 10, img: '/img/products/zamek-alu.jpg', desc_long: 'Nerezové závodní čepy kapoty se závlačkami.', desc_long_en: 'Stainless steel racing bonnet pins with clips.', specs: [['Materiál', 'Nerezová ocel leštěná'], ['Průměr čepu', '6 mm']], specs_en: [['Material', 'Polished stainless steel'], ['Pin diameter', '6 mm']] },
    { id: 19, name: 'Svorka výfuku 2.5" nerez', name_en: 'Exhaust clamp 2.5" stainless', category: 'karoserie', price: 320, desc: 'Nerezová svorka výfuku 63,5 mm (2.5"). V-band provedení.', desc_en: 'Stainless steel exhaust clamp 63.5 mm (2.5"). V-band type.', badge: '', stock: 25, img: '/img/products/flexi-vyfuk.jpg', desc_long: 'V-band svorka výfuku z nerezové oceli pro trubku 63,5 mm.', desc_long_en: 'Stainless steel V-band exhaust clamp for 63.5 mm pipe.', specs: [['Materiál', 'Nerezová ocel'], ['Průměr', '63.5 mm (2.5")']], specs_en: [['Material', 'Stainless steel'], ['Diameter', '63.5 mm (2.5")']] },
    { id: 20, name: 'Flexi hadice výfuku 2.5"', name_en: 'Exhaust flexi pipe 2.5"', category: 'karoserie', price: 650, desc: 'Nerezová flexibilní hadice výfuku 63,5 mm. Délka 200 mm.', desc_en: 'Stainless steel flexible exhaust pipe 63.5 mm. Length 200 mm.', badge: '', stock: 12, img: '/img/products/flexi-vyfuk.jpg', desc_long: 'Nerezová flexibilní hadice výfuku pro tlumení vibrací motoru.', desc_long_en: 'Stainless steel flexible exhaust pipe for damping engine vibrations.', specs: [['Materiál', 'Nerezová ocel'], ['Vnitřní průměr', '63.5 mm']], specs_en: [['Material', 'Stainless steel'], ['Inner diameter', '63.5 mm']] },
    { id: 21, name: 'Banner Running Bull AGM', name_en: 'Banner Running Bull AGM', category: 'baterie', price: 4590, desc: 'AGM baterie Banner Running Bull 70Ah. Start-Stop technologie.', desc_en: 'AGM battery Banner Running Bull 70Ah. Start-Stop technology.', badge: '', stock: 5, img: '/img/products/banner-baterie.jpg', desc_long: 'Prémiová AGM baterie Banner Running Bull s kapacitou 70Ah.', desc_long_en: 'Premium AGM battery Banner Running Bull with 70Ah capacity.', specs: [['Technologie', 'AGM'], ['Kapacita', '70 Ah']], specs_en: [['Technology', 'AGM'], ['Capacity', '70 Ah']] },
    { id: 22, name: 'Exide Start-Stop AGM', name_en: 'Exide Start-Stop AGM', category: 'baterie', price: 3890, desc: 'AGM baterie Exide 60Ah. Ideální pro motorsport i běžný provoz.', desc_en: 'AGM battery Exide 60Ah. Ideal for motorsport and daily driving.', badge: '', stock: 4, img: '/img/products/banner-professional.jpg', desc_long: 'AGM baterie Exide s kapacitou 60Ah a startovacím proudem 680A.', desc_long_en: 'AGM battery Exide with 60Ah capacity and 680A cranking power.', specs: [['Technologie', 'AGM'], ['Kapacita', '60 Ah']], specs_en: [['Technology', 'AGM'], ['Capacity', '60 Ah']] },
    { id: 23, name: 'Varta Silver Dynamic', name_en: 'Varta Silver Dynamic', category: 'baterie', price: 3290, desc: 'Varta Silver Dynamic 74Ah. Vysoký startovací proud pro spolehlivý start.', desc_en: 'Varta Silver Dynamic 74Ah. High cranking power for reliable starts.', badge: 'sale', stock: 7, img: '/img/products/varta.png', desc_long: 'Varta Silver Dynamic — prémiová baterie s kapacitou 74Ah.', desc_long_en: 'Varta Silver Dynamic — premium battery with 74Ah capacity.', specs: [['Technologie', 'PowerFrame'], ['Kapacita', '74 Ah']], specs_en: [['Technology', 'PowerFrame'], ['Capacity', '74 Ah']] },
    { id: 24, name: 'Banner Starting Bull', name_en: 'Banner Starting Bull', category: 'baterie', price: 2190, desc: 'Banner Starting Bull 44Ah. Lehká baterie pro závodní aplikace.', desc_en: 'Banner Starting Bull 44Ah. Lightweight battery for racing applications.', badge: '', stock: 10, img: '/img/products/banner-baterie.jpg', desc_long: 'Banner Starting Bull — kompaktní a lehká baterie s kapacitou 44Ah.', desc_long_en: 'Banner Starting Bull — compact and lightweight battery with 44Ah capacity.', specs: [['Technologie', 'Klasická (Ca/Ca)'], ['Kapacita', '44 Ah']], specs_en: [['Technology', 'Conventional (Ca/Ca)'], ['Capacity', '44 Ah']] },
    { id: 25, name: 'Test produkt', name_en: 'Test product', category: 'motor', price: 0, desc: 'Testovací produkt za 0 Kč pro ověření objednávkového procesu.', desc_en: 'Test product at 0 CZK for testing the order process.', badge: 'new', stock: 99, img: '/img/products/remenice-red.png', desc_long: '', desc_long_en: '', specs: [], specs_en: [] }
];

var SEED_GALLERY = [
    { id: 'static-gallery-1', filename: 'race-car.jpg', url: '/img/gallery/race-car.jpg', type: 'image/jpeg', tags: ['gallery'], static: true },
    { id: 'static-gallery-2', filename: 'pu-silentbloky.png', url: '/img/gallery/pu-silentbloky.png', type: 'image/png', tags: ['gallery'], static: true },
    { id: 'static-gallery-3', filename: 'mezihorak.jpg', url: '/img/gallery/mezihorak.jpg', type: 'image/jpeg', tags: ['gallery'], static: true },
    { id: 'static-gallery-4', filename: 'remenice.png', url: '/img/gallery/remenice.png', type: 'image/png', tags: ['gallery'], static: true },
    { id: 'static-gallery-5', filename: 'kovoobrabeeni.png', url: '/img/gallery/kovoobrabeeni.png', type: 'image/png', tags: ['gallery'], static: true },
    { id: 'static-gallery-6', filename: 'servis.png', url: '/img/gallery/servis.png', type: 'image/png', tags: ['gallery'], static: true },
    { id: 'static-gallery-7', filename: 'vyvlecka-rally.jpg', url: '/img/gallery/vyvlecka-rally.jpg', type: 'image/jpeg', tags: ['gallery'], static: true },
    { id: 'static-gallery-8', filename: 'mezihorak-rally.jpg', url: '/img/gallery/mezihorak-rally.jpg', type: 'image/jpeg', tags: ['gallery'], static: true },
    { id: 'static-gallery-9', filename: 'ruzicka-rally.jpg', url: '/img/gallery/ruzicka-rally.jpg', type: 'image/jpeg', tags: ['gallery'], static: true },
    { id: 'static-gallery-10', filename: 'sklenar-crx.jpg', url: '/img/gallery/sklenar-crx.jpg', type: 'image/jpeg', tags: ['gallery'], static: true },
    { id: 'static-gallery-11', filename: 'workshop.jpg', url: '/img/gallery/workshop.jpg', type: 'image/jpeg', tags: ['gallery'], static: true },
    { id: 'static-gallery-12', filename: 'team-photo.jpg', url: '/img/gallery/team-photo.jpg', type: 'image/jpeg', tags: ['gallery'], static: true }
];

var SEED_POSTS = [
    { slug: 'rally-magazin', title: 'Rally Magazín — Rozhovor', category: 'Reportáže', date: '2021', excerpt: 'Rozhovor s bratry Mezihoráky v Rally Magazínu o závodní kariéře a cestě k motorsportu.', coverImage: '/img/blog/rally-magazin.jpg', published: true, content: '<p>Rozhovor s bratry Mezihoráky v Rally Magazínu o závodní kariéře a cestě k motorsportu. Silponix jako technický partner týmu.</p>' },
    { slug: 'koprivnice-mm', title: 'M&M v Kopřivnici — 1. místo', category: 'Závody', date: '2020', excerpt: 'Marek Horák a Michal Mensl vyhráli 1. místo ve třídě 1600 ccm na polygonu TATRA Kopřivnice.', coverImage: '/img/blog/koprivnice.jpg', published: true, content: '<p>Marek Horák a Michal Mensl vyhráli 1. místo ve třídě 1600 ccm na polygonu TATRA Kopřivnice.</p>' },
    { slug: 'bratri-hemerkovi', title: 'České barvy pochyběly v Top10', category: 'Závody', date: '2021', excerpt: 'Bratři Hemerkovi na Dakaru 2021. Podrobná reportáž z nejtěžšího závodu světa.', coverImage: '/img/blog/bratri-hemerkovi.jpg', published: true, content: '<p>České barvy na Dakaru 2021. Bratři Hemerkovi s technikou připravenou v Silponix.</p>' },
    { slug: 'kowax-valmez-2020', title: 'Kowax Valašská Rally ValMez', category: 'Závody', date: '2020', excerpt: 'Silponix Racing na Kowax Valašské Rally ValMez 2020. Příprava vozu a závodní víkend.', coverImage: '/img/blog/kowax-valmez.jpg', published: true, content: '<p>Silponix Racing na Kowax Valašské Rally ValMez 2020.</p>' },
    { slug: 'honda-crx-rallycross', title: 'Žlutá Honda CRX — SuperTouringCars', category: 'Závody', date: '2020', excerpt: 'Michal Sklenář v rallycrossu v Sedlčanech, 2. místo ve třídě SuperTouringCars 1600.', coverImage: '/img/blog/honda-crx-rallycross.jpg', published: true, content: '<p>Michal Sklenář v rallycrossu v Sedlčanech s Honda CRX připravenou v Silponix.</p>' },
    { slug: 'rally-vyskov', title: 'XXVI. Rally Vyškov', category: 'Závody', date: '2020', excerpt: 'Rally Vyškov 2020 — Mezihorák na 35. místě celkově, Růžička 42. Dva poháry ve třídách.', coverImage: '/img/blog/rally-vyskov.jpg', published: true, content: '<p>Rally Vyškov 2020 — výsledky Silponix Racing týmu.</p>' },
    { slug: 'hemerka-debut', title: 'Hemerkův debut na Barum Rally', category: 'Závody', date: '2020', excerpt: 'Martin Hemerka debutoval na Barum Czech Rally Zlín 2020 s Hondou Civic EK4.', coverImage: '/img/blog/hemerka-debut.jpg', published: true, content: '<p>Martin Hemerka debutoval na Barum Czech Rally Zlín 2020.</p>' },
    { slug: 'sedlcany-rallycross', title: 'Po dlouhé pauze — Rallycross Sedlčany', category: 'Závody', date: '2020', excerpt: 'Návrat po COVID pauze. Test nové převodovky Hewland na Honda CRX Michala Sklenáře.', coverImage: '/img/blog/sedlcany-rallycross.jpg', published: true, content: '<p>Návrat po COVID pauze. Test nové převodovky Hewland na Honda CRX.</p>' },
    { slug: 'zlaty-venec', title: 'Zlatý věnec v Sedlčanské kotlini', category: 'Závody', date: '2020', excerpt: 'Silponix Racing na tradičním závodě do vrchu Zlatý věnec v Sedlčanské kotlini.', coverImage: '/img/blog/zlaty-venec.jpg', published: true, content: '<p>Silponix Racing na závodě do vrchu Zlatý věnec.</p>' },
    { slug: 'dvh-racing', title: 'DVH Racing — Kowax Valmez Rally', category: 'Závody', date: '2020', excerpt: 'Partner DVH Racing na Kowax Valašské Rally ValMez 2020 s vozem připraveným v dílně Silponix.', coverImage: '/img/blog/kowax-valmez.jpg', published: true, content: '<p>Partner DVH Racing na Kowax Valašské Rally ValMez 2020.</p>' },
    { slug: 'carbonia-cup', title: 'SForza Racing — Carbonia Cup Most', category: 'Závody', date: '2019', excerpt: 'Silponix Racing a SForza Racing na okruhovém závodě Carbonia Cup v Mostě.', coverImage: '/img/blog/carbonia-cup.jpg', published: true, content: '<p>Silponix Racing a SForza Racing na Carbonia Cup v Mostě.</p>' },
    { slug: 'kromeriz-rally', title: '1. Rallye Kroměříž', category: 'Závody', date: '2019', excerpt: 'Inaugurační Rally Kroměříž. Vyvlečka/Mudrák 14./130, 4. ve třídě A2.', coverImage: '/img/blog/kromeriz-rally.jpg', published: true, content: '<p>Inaugurační Rally Kroměříž — Vyvlečka/Mudrák 14. celkově.</p>' },
    { slug: 'barum-rally-2019', title: '49. Barum Czech Rally Zlín 2019', category: 'Závody', date: '2019', excerpt: 'Vyvlečka/Mudrák vedli ve třídě, ale v neděli odstoupili kvůli únavě materiálu.', coverImage: '/img/blog/barum-rally.jpg', published: true, content: '<p>Barum Czech Rally Zlín 2019 — Vyvlečka/Mudrák vedli ve třídě.</p>' }
];

module.exports = { SEED_PRODUCTS, SEED_GALLERY, SEED_POSTS };
